services:
  analysis-starter:
    image: analysis-starter
    container_name: analysis-starter
    build: ./AnalysisStarter
    ports:
      - "${ANALYSIS_STARTER_BOUND_PORT}:${ANALYSIS_STARTER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  engine-analysis:
    image: engine-analysis
    container_name: engine-analysis
    build: ./EngineAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  exhaust-mounting-analysis:
    image: exhaust-mounting-analysis
    container_name: exhaust-mounting-analysis
    build: ./ExhaustMountingAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  fluid-analysis:
    image: fluid-analysis
    container_name: fluid-analysis
    build: ./FluidAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  gearbox-options-analysis:
    image: gearbox-options-analysis
    container_name: gearbox-options-analysis
    build: ./GearBoxOptionsAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  starting-system-analysis:
    image: starting-system-analysis
    container_name: starting-system-analysis
    build: ./StartingSystemAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

  transmission-analysis:
    image: transmission-analysis
    container_name: transmission-analysis
    build: ./TransmissionAnalysis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
